import Head from "next/head";
import styles from "../styles/Home.module.css";
import FormMonitor from "./components/form-monitor";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Live Chat Monitoring</h1>
        <p className={styles.description}>
          Start monitoring by writing and YouTube Live URL
        </p>
        <FormMonitor styles={styles} />
      </main>
      <footer className={styles.footer}>Chat Monitor</footer>
    </div>
  );
}
